name: Nuget
on:
  pull_request:
    types: [closed]
  #pull_request_review:
    #types: [submitted]

jobs:
  pushToNuget:
    #if: github.event.review.state == 'approved
    name: Deploy to Nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Pack
      working-directory: HttpBase
      run: dotnet build --configuration Release && dotnet pack --configuration Release -o out -p:PackageVersion=1.0.2 
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
          name: nupkg
          path: HttpBase/out/*.nupkg
    - name: Push
      working-directory: HttpBase/out/
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET }} -s https://api.nuget.org/v3/index.json --skip-duplicate --no-symbols
