name: Nuget
on:
  push:
    branches:
    - main
  pull_request:
    types: [closed]
    branches:
    - main

jobs:
  pushToNuget:
    name: Deploy to Nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: ls
      working-directory: HttpBase
      run: ls
    - name: Pack
      working-directory: HttpBase
      run: dotnet pack --configuration Release -o out
    - name: Push
      working-directory: HttpBase/out/
      run: ls
